Starting coarse data computation...
Processing year: 1950
Importing 12 files
Calculating pv mean
Program took 21.4223 seconds
Processing year: 1951
Importing 12 files
Calculating pv mean
Program took 31.3083 seconds
Processing year: 1952
Importing 12 files
Calculating pv mean
Program took 27.6806 seconds
Processing year: 1953
Importing 12 files
Calculating pv mean
Program took 30.7907 seconds
Processing year: 1954
Importing 12 files
Calculating pv mean
Program took 26.9450 seconds
Processing year: 1955
Importing 12 files
Calculating pv mean
Program took 28.1786 seconds
Processing year: 1956
Importing 12 files
Calculating pv mean
Program took 36.9195 seconds
Processing year: 1957
Importing 12 files
Calculating pv mean
Program took 39.6539 seconds
Processing year: 1958
Importing 12 files
Calculating pv mean
Program took 34.7122 seconds
Processing year: 1959
Importing 12 files
Calculating pv mean
Program took 36.6855 seconds
Processing year: 1960
Importing 12 files
Calculating pv mean
Program took 38.2219 seconds
Processing year: 1961
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1961. Continuing to next year...
Processing year: 1962
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1962. Continuing to next year...
Processing year: 1963
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1963. Continuing to next year...
Processing year: 1964
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1964. Continuing to next year...
Processing year: 1965
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1965. Continuing to next year...
Processing year: 1966
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1966. Continuing to next year...
Processing year: 1967
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1967. Continuing to next year...
Processing year: 1968
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1968. Continuing to next year...
Processing year: 1969
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1969. Continuing to next year...
Processing year: 1970
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1970. Continuing to next year...
Processing year: 1971
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1971. Continuing to next year...
Processing year: 1972
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1972. Continuing to next year...
Processing year: 1973
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1973. Continuing to next year...
Processing year: 1974
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1974. Continuing to next year...
Processing year: 1975
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1975. Continuing to next year...
Processing year: 1976
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1976. Continuing to next year...
Processing year: 1977
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1977. Continuing to next year...
Processing year: 1978
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1978. Continuing to next year...
Processing year: 1979
Importing 2 files
Calculating pv mean
Program took 7.7208 seconds
Processing year: 1980
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1980. Continuing to next year...
Processing year: 1981
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1981. Continuing to next year...
Processing year: 1982
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1982. Continuing to next year...
Processing year: 1983
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1983. Continuing to next year...
Processing year: 1984
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1984. Continuing to next year...
Processing year: 1985
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1985. Continuing to next year...
Processing year: 1986
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1986. Continuing to next year...
Processing year: 1987
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1987. Continuing to next year...
Processing year: 1988
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1988. Continuing to next year...
Processing year: 1989
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1989. Continuing to next year...
Processing year: 1990
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1990. Continuing to next year...
Processing year: 1991
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1991. Continuing to next year...
Processing year: 1992
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1992. Continuing to next year...
Processing year: 1993
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1993. Continuing to next year...
Processing year: 1994
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1994. Continuing to next year...
Processing year: 1995
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1995. Continuing to next year...
Processing year: 1996
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1996. Continuing to next year...
Processing year: 1997
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1997. Continuing to next year...
Processing year: 1998
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1998. Continuing to next year...
Processing year: 1999
Importing 0 files
Traceback (most recent call last):
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 49, in <module>
    main(args.year, client)
  File "/home/yannickh00/ICM/Europe_Task/comp_coarse_cutting_pvpot.py", line 26, in main
    ds=xr.open_mfdataset(all_files,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/jupyterhub/lib/python3.12/site-packages/xarray/backends/api.py", line 1541, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Error processing year 1999. Continuing to next year...
Processing year: 2000
Importing 12 files
Calculating pv mean
Program took 27.5255 seconds
Processing year: 2001
Importing 12 files
Calculating pv mean
Program took 23.9394 seconds
Processing year: 2002
Importing 12 files
Calculating pv mean
Program took 23.7516 seconds
Processing year: 2003
Importing 12 files
Calculating pv mean
Program took 24.2452 seconds
Processing year: 2004
Importing 12 files
Calculating pv mean
Program took 22.9591 seconds
Processing year: 2005
Importing 12 files
Calculating pv mean
Program took 24.9292 seconds
Processing year: 2006
Importing 12 files
Calculating pv mean
Program took 22.9485 seconds
Processing year: 2007
Importing 12 files
Calculating pv mean
Program took 25.1881 seconds
Processing year: 2008
Importing 12 files
Calculating pv mean
Program took 26.8168 seconds
Processing year: 2009
Importing 12 files
Calculating pv mean
Program took 24.1055 seconds
Processing year: 2010
Importing 12 files
Calculating pv mean
Program took 24.1135 seconds
Coarse data computation completed for all years
